# Generated by Django 2.0.2 on 2018-03-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
